spring:
    application:
        name: App
    datasource:
        url: jdbc:mysql://localhost:3306/fitnessapp
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                show-sql: true
                format_sql: true


jwt_secret: hemlignycket

inspector:
    ingestion-key:
        b5f51901972fecd3c1903ca788933a8484b90639

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace


